name: voxy_stk_push
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  dart_appwrite: 8.0.0
  dio: ^5.4.0
  firedart: ^0.9.8
  intl: ^0.19.0
  json_annotation: 4.8.1
  json_serializable: 6.7.1


dev_dependencies:
  lints: ^2.0.0
  build_runner: 2.4.7
